project_id = "yvalikcxmtegqsiymfkn"

[functions.generate-suggestions]
verify_jwt = true

[functions.purge-old-tasks]
verify_jwt = false

[functions.sync-canvas]
verify_jwt = true

[functions.google-calendar-oauth]
verify_jwt = false

[functions.sync-google-calendar]
verify_jwt = true
